#ifndef SERVICES_MODULATIONS_FSK_FSK_PSEUDO_2FSK_H
#define SERVICES_MODULATIONS_FSK_FSK_PSEUDO_2FSK_H

#include "fsk.h"

/*
 * Initiates pseudo random transmition 2FSK mode. 
 * In this mode a random data are generated by the internal pseudo-random generator.
 * Modulation type is 2FSK, where two different frequencies are used so the generated stream will be hearable
 * on FM receiver.
 */
bool fsk_init_tx_pseudo_sync_2fsk();


#endif